[build]
publish = "dist"
command = "npm run build"

[[redirects]]
from = "/"
to = "/index-sl.html"
status = 200

[[redirects]]
from = "/index.html"
to = "/index-sl.html"
status = 301

[[redirects]]
from = "/admin/*"
to = "/admin/index.html"
status = 200